# Generated by Django 4.2.3 on 2023-07-27 10:34

import Plattypus.account.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=254, validators=[Plattypus.account.validators.email_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
