# Generated by Django 4.2.3 on 2023-07-30 08:47

import Plattypus.account.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_plattypususer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plattypususer',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, validators=[Plattypus.account.validators.minimum_age_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plattypususer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Do not show', 'Do not show'), ('Male', 'Male')], max_length=12),
        ),
    ]
