# Generated by Django 4.2.3 on 2023-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_plattypususer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plattypususer',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Do not show', 'Do not show'), ('Male', 'Male')], max_length=12),
        ),
        migrations.AlterField(
            model_name='plattypususer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
