# Generated by Django 4.2.3 on 2023-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_plattypususer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plattypususer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Do not show', 'Do not show'), ('Female', 'Female')], max_length=12),
        ),
    ]
