# Generated by Django 4.2.3 on 2023-07-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_expense_date_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('BGN', 'BGN'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('INR', 'INR'), ('JPY', 'JPY')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('BGN', 'BGN'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('INR', 'INR'), ('JPY', 'JPY')]),
        ),
    ]
