# Generated by Django 4.2.3 on 2023-07-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_rename_to_profile_expense_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_profile',
            new_name='user',
        ),
    ]
