# Generated by Django 4.2.3 on 2023-07-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_income_source_savings_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
