# Generated by Django 4.2.3 on 2023-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_rename_source_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='currency',
            field=models.CharField(choices=[('BGN', 'BGN'), ('GBP', 'GBP'), ('EUR', 'EUR'), ('USD', 'USD'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('INR', 'INR'), ('JPY', 'JPY')], default='EUR'),
            preserve_default=False,
        ),
    ]
